"""add_onboarding_completed

Revision ID: f6385f6577d5
Revises: 0001_initial
Create Date: 2026-07-06 12:09:36.706761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6385f6577d5'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role_permissions', ['role_id', 'permission_id'])
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET onboarding_completed = FALSE")
    op.alter_column('users', 'onboarding_completed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_constraint(None, 'role_permissions', type_='unique')
    # ### end Alembic commands ###
